#!/bin/bash
CURRENT_DIR=`pwd` # etc/apps/faup/bin/ where faup.py is
FAUP_BINARY=$CURRENT_DIR/../opt/macos-x86_64/bin/faup
FAUP_LIBDIR=$CURRENT_DIR/../opt/macos-x86_64/lib
export LD_LIBRARY_PATH=$FAUP_LIBDIR
export FAUP_DATA_DIR="$CURRENT_DIR/../opt/macos-x86_64/share/faup"

# XXX: I haven't passed my MacOSX degree yet. Is it seriously the only way I can point out the binary to a given library?
# if yes, "Ah ah ah ah!", if not, please tell me how.
if [ ! -f .relocated ]
then
    faup_libfrom=`otool -L $FAUP_BINARY |grep libfaupl.1.dylib |awk '{print $1}'`
    lua_libfrom=`otool -L $FAUP_LIBDIR/libfaupl.1.dylib |grep liblua.dylib |awk '{print $1}'`

    install_name_tool -change $faup_libfrom $FAUP_LIBDIR/libfaupl.1.dylib $FAUP_BINARY
    install_name_tool -change $lua_libfrom $FAUP_LIBDIR/liblua.dylib $FAUP_LIBDIR/libfaupl.1.dylib

    touch .relocated
fi

$FAUP_BINARY $@

